### ISSUE TITLE
Latest version 1.5.3 is missing

### ISSUE THREAD

**Issue by CrisFavero** [romkatv/homebrew-gitstatus#1]

**Comment by romkatv** [comment]
The only change in v1.5.3 is related to FreeBSD:

- Rebuild `gitstatusd-freebsd-amd64` with clang to make it work on FreeBSD 13 (#262).

**Comment by CrisFavero** [comment]
This fix which lannded after 1.5.2 
https://github.com/romkatv/gitstatus/commit/7001409ed3d363373fce09e95e6ddb00787bcae8
fixes an issue with the terminal width not being reported correctly  for me in bash on mac

**Comment by romkatv** [comment]
Sorry about that. I've released v1.5.3.

P.S.

If you mentioned that up front, that would've helped. In general, I hold in very low esteem issues and PRs that don't do anything useful for the reporter. The issue and the PR you've filed looked just like that. "Latest version is missing" doesn't say why you care. It looks like a random drive by.

**Comment by CrisFavero** [comment]
Thats Fair I was just making the commits super late at night here so I was looking to just get it out I'll try and keep that in mind when opening future PRs in yours and others repos. Thanks
